### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by sainsaji** [michaelparkadze/angular-ecommerce-app#2]
Its throwing error
![image](https://user-images.githubusercontent.com/95070425/165923205-659210c8-63b4-4aca-8124-bd7532daa72a.png)

![image](https://user-images.githubusercontent.com/95070425/165923430-248bc8c6-e5a6-4342-b47b-89c9c289f89b.png)

cart project page everything is working well.
Good Effort

**Comment by VinhKyiT** [comment]
change "full_name" in line 68 to "fname" it works for me

**Comment by michaelparkadze** [comment]
> change "full_name" in line 68 to "fname" it works for me

You could create a quick PR Fix of this and I will merge it ;)

**Comment by VinhKyiT** [comment]
> > change "full_name" in line 68 to "fname" it works for me
> 
> You could create a quick PR Fix of this and I will merge it ;)

Can I have the permission to push the code

**Comment by michaelparkadze** [comment]
You can fork the repo, have your changed commited and pushed and then create a PR so I could review it and merge it into the current codebase :)

**Comment by michaelparkadze** [comment]
> > > change "full_name" in line 68 to "fname" it works for me
> > 
> > 
> > You could create a quick PR Fix of this and I will merge it ;)
> 
> Can I have the permission to push the code

You can fork the repo, have your changed commited and pushed and then create a PR so I could review it and merge it into the current codebase :)

**Comment by VinhKyiT** [comment]
> > > > change "full_name" in line 68 to "fname" it works for me
> > > 
> > > 
> > > You could create a quick PR Fix of this and I will merge it ;)
> > 
> > 
> > Can I have the permission to push the code
> 
> You can fork the repo, have your changed commited and pushed and then create a PR so I could review it and merge it into the current codebase :)

I created the PR bro, let's review it

**Comment by michaelparkadze** [comment]
this issue was fixed :)
